### ISSUE TITLE
Is this a success? MACOS cpu for intel

### ISSUE THREAD

**Issue by hyh019** [iron-fish/ironfish#1096]
### Description

Is this a success?MACOS cpu for intel
I'm a newbie and I don't know what counts as success，hahaha
![WechatIMG40](https://user-images.githubusercontent.com/6009571/156886968-57ab55d8-6be1-483b-b7cb-fbc67b6952dc.jpeg)

**Comment by AmberKiso** [comment]
This is expected behavior. Your node is not yet fully synchronized.
In the left window the last progress indicator is at 9.81%
You can run the miners:start command while the node is syncing, but mining will not start until the node is at 100%

You can ask questions in the Iron Fish #questions channel to get a faster response.
https://discord.com/channels/771503434028941353/828767731305676810

**Comment by deekerno** [comment]
The above response is exactly correct. Thanks for answering that, @AmberKiso!
