### ISSUE TITLE
deposit bug

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#1301]
### What happened?

Misleading messages regarding insufficient balance 
![deposit](https://user-images.githubusercontent.com/43998465/167732388-f17667ad-bc73-4e02-8dce-4ab78a163e26.png)
!

### Version

v0.1.32

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.32 @ 1abccc9
Iron Fish library       0.0.10 @ 1abccc9
Operating system        Windows_NT x64
CPU model(s)            AMD Ryzen 9 5950X 16-Core Processor
CPU threads             32
RAM total               63.92 GiB
Node version            v16.13.2
ironfish in PATH        true
Telemetry enabled       true
```

### Graffiti

Qualia

**Comment by deekerno** [comment]
This is due to how notes are consumed for transactions on the node. When creating a transaction, notes are used as inputs to furnish the desired transaction amount plus the fee. You will receive your change in the form of output notes which are then stored in your wallet, but only after your transaction has been confirmed by the network and included in a block. The balance during your transaction is the sum of all of the unconsumed notes; the balance after your transaction has been confirmed includes the aforementioned balance plus the output notes (if any) of said transaction.

That being said, there is potential for improving the wording regarding balances, and we'll look into that.
