### ISSUE TITLE
Deposit failing with insufficient balance error even though account has enough balance

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1307]
### What happened?

Steps followed:
Account has balance of ~0.2
Initiated a deposit using the command "ironfish deposit"
But it failed with a message - insufficient balance

![Insufficient balance error](https://user-images.githubusercontent.com/53503800/167783370-51ad2f01-6f63-4dbe-a086-f971da3ba67c.jpg)
e

### Version

0.1.32

### Graffiti

johnsgeorge

**Comment by deekerno** [comment]
This is due to how notes are consumed for transactions on the node. When creating a transaction, notes are used as inputs to furnish the desired transaction amount plus the fee. You will receive your change in the form of output notes which are then stored in your wallet, but only after your transaction has been confirmed by the network and included in a block. The balance during your transaction is the sum of all of the unconsumed notes; the balance after your transaction has been confirmed includes the aforementioned balance plus the output notes (if any) of said transaction.

That being said, there is potential for improving the wording regarding balances, and we'll look into that.
