### ISSUE TITLE
[incorrect balance due ironfish deposit ]

### ISSUE THREAD

**Issue by toolfun** [iron-fish/ironfish#1316]
### What happened?

When executing the **ironfish deposit** command, the balance in the terminal is displayed incorrectly. This is confusing because it is unclear how much more **$IRON** can be spent.

### Version

0.1.32

### Debug output

```shell
ironfish debug
yarn run v1.22.18
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.32 @ src
Iron Fish library       0.0.10 @ src
Operating system        Linux x64
CPU model(s)            Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
CPU threads             16
RAM total               62.51 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
Done in 1.84s.
```

### Graffiti

spyhook

**Comment by deekerno** [comment]
This is due to how notes are consumed for transactions on the node. When creating a transaction, notes are used as inputs to furnish the desired transaction amount plus the fee. You will receive your change in the form of output notes which are then stored in your wallet, but only after your transaction has been confirmed by the network and included in a block. The balance during your transaction is the sum of all of the unconsumed notes; the balance after your transaction has been confirmed includes the aforementioned balance plus the output notes (if any) of said transaction.

That being said, there is potential for improving the wording regarding balances, and we'll look into that.

**Comment by toolfun** [comment]
Ok, thanks for the comment. Perhaps until this has been improved, issue a short note in the command output that will explain and reassure the user.
