### ISSUE TITLE
bag after ironfish deposit

### ISSUE THREAD

**Issue by gutkati** [iron-fish/ironfish#1326]
### What happened?

![ironfish](https://user-images.githubusercontent.com/94618780/167931116-3977c334-fe5c-484c-a1bd-d2bda76a9a48.PNG)
![ironfish2](https://user-images.githubusercontent.com/94618780/167932694-57f10ebd-d824-4e94-896d-a3a5b751f71a.PNG)

### Version

0.1.32

### Debug output

```shell
Iron Fish version            0.1.32 @ src
Iron Fish library            0.0.10 @ src
Operating system             Linux x64
CPU model(s)                 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
CPU threads                  40
RAM total                    3.81 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           00000000000333ab37f6145bcfd600686d00729c52745e5055d6255deb6d0245
Accounts head in chain       true
Accounts head sequence       1535
Done in 4.92s.
```

### Graffiti

cryptostarscream

**Comment by deekerno** [comment]
This is due to how notes are consumed for transactions on the node. When creating a transaction, notes are used as inputs to furnish the desired transaction amount plus the fee. You will receive your change in the form of output notes which are then stored in your wallet, but only after your transaction has been confirmed by the network and included in a block. The balance during your transaction is the sum of all of the unconsumed notes; the balance after your transaction has been confirmed includes the aforementioned balance plus the output notes (if any) of said transaction.

That being said, there is potential for improving the wording regarding balances, and we'll look into that.
