### ISSUE TITLE
Discord Hook

### ISSUE THREAD

**Issue by Masternode24** [iron-fish/ironfish#1541]
### What happened?

Hi,

After 2 days discord hook not working ...
We will provide you all what you need to investigate.
Ask us in DISCORD!

P.S. in logs all looks correctly.

BR,
Masternode24.de

### Version

0.35

### Graffiti

Masternode24.de

**Comment by mat-if** [comment]
To confirm you've done the following steps:
1. Configure a webhook for your discord server: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks (ignore the "Quick Example" since it's for Github specifically, not useful here.)
2. You took that webhook url and did `ironfish config:set poolDiscordWebhook webhook-url-from-step-1`
3. Restarted the pool

**Comment by lwisne** [comment]
Did this work?
