### ISSUE TITLE
Transaction fails, but message shows success.

### ISSUE THREAD

**Issue by Miraell** [iron-fish/ironfish#1628]
### Description

Transaction fails, but there is no appropriate message for that.

AR: Transaction message - success, balance did not decrease
ER:  Transaction message - failed, balance  did not decrease. OR Transaction message - success, balance decreased.

```
You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000001 ($ORE 1) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 0.75453118 ($ORE 75,453,118).
The memo will contain the graffiti "DmitryPNode".

* This action is NOT reversible *
      
Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from DmitryPNode
Transaction Hash: ef18b6f9abaed15629e57ad774ec8ab9272889012d01ba0819b2f9832aa9a73e
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/ef18b6f9abaed15629e57ad774ec8ab9272889012d01ba0819b2f9832aa9a73e (it can take a few minutes before the transaction appears in the Explorer)
Done in 1957.80s.
root@srv20436:~# ironfish deposit
yarn run v1.22.18
$ yarn build && yarn start:js deposit
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run deposit

You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000001 ($ORE 1) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 0.75453118 ($ORE 75,453,118).
The memo will contain the graffiti "DmitryPNode".

* This action is NOT reversible *
      
Do you confirm (Y/N)?: Y 
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

**Comment by mat-if** [comment]
Hi @Miraell, thanks for reporting this.

If I'm understanding this correctly, this isn't really a bug, but rather some unclear behavior.

The only thing the deposit knows is whether the transaction was successfully created and sent out to your peers. Beyond that, it has no way of knowing whether it succeeded or not until one of two things happens:
1. The transaction is picked up by a miner and put into a block at some future time (this can take upwards of 15 minutes in some cases)
2. The transaction never gets picked up before the expiration sequence is hit (by default, it is 15 blocks from when you created the transaction).

So there's really 2 things happening here:
1. Whether a transaction was successfully _created_. This is what the `deposit` command checks for
2. Whether a transaction is picked up and put into a block by a miner. This takes more time, and would be really annoying to have the deposit command wait for this.

We currently have a known issue where some transactions are struggling to gossip properly throughout the network, but we expect this to be fixed in the next release.
