### ISSUE TITLE
[FIP] JSON Rpc over http

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#1676]
### Description

Rpc call over tcp has been supported now. This FIP proposes to support Rpc call over http.

**Comment by NullSoldier** [comment]
So this is just doing RPC calls over HTTP, and not implementation of JSON RPC 2.0 right? If so I 100% support this, as it's on our roadmap for us to build.

It should go in a new adapter. Unfortunately since it's not a net.Socket based adapter you cannot inherit from RpcSocketAdapter, so you may need to duplicate a little bit of logic for your new adapter unless you can redo the abstractions a bit.

**Comment by hairtail** [comment]
Actually, what I think we should do is implementation of JSON RPC 2.0. You know, JSON RPC is kind of widely used [message request/response struct standard](https://www.jsonrpc.org/specification). But, yes we should refactor most of request/response struct.

**Comment by lwisne** [comment]
In fact, I'm going to do that

**Comment by lwisne** [comment]
Split out into https://github.com/iron-fish/ironfish/issues/1923 and https://github.com/iron-fish/ironfish/issues/1922
