### ISSUE TITLE
Slow response to rpc request over tcp 

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#2151]
### What happened?

As my node keeps running, response of rpc request over tcp is slower and slower. Then I have to restart my node.

### Version

0.1.44 @ src

### Graffiti

miningKing

**Comment by NullSoldier** [comment]
The issue is a general CPU usage issue rather than RPC issue. Node is single threaded so when the main thread is blocked, it cannot respond to the RPC layer. We're working on general CPU optimization to resolve this, but this is not a fixable bug with one ticket but many parts of the code base that need to be optimized.
