### ISSUE TITLE
Print node status (cli)

### ISSUE THREAD

**Issue by zenoxygen** [iron-fish/ironfish#23]
#### Description
Bug in ironfish-cli to print node status.

#### Config
Default ironfish-cli configuration, with Linux 5.11.11-arch1-1.

#### To Reproduce
```
ironfish status -f
TypeError: Cannot read property 'screen' of undefined
```

**Comment by dguenther** [comment]
This is probably built from source if it's on arch, right? That error would indicate it can't find certain packages, so it might be an issue with how the node is being started. Do you have `ironfish` aliased to something?

**Comment by zenoxygen** [comment]
Yes, built from source on Arch, with alias ironfish="ironfish/ironfish-cli/bin/run".
I was unable to start the node, like #11.
I used `yarn start:js start` to start the node, from ironfish-cli directory.

**Comment by dguenther** [comment]
Got it, I updated the docs to remove the reference to `alias ironfish="ironfish/ironfish-cli/bin/run"`, since that doesn't work correctly when built from source. If you still wanted to use an alias, you could do something like this:

```
function ironfish() { (cd ironfish/ironfish-cli; yarn start:js $@) }
```

Closing this since I believe it should be fixed in our documentation now, thanks for filing an issue!

**Comment by zenoxygen** [comment]
Awesome, I confirm it works perfectly now. Thanks.
