### ISSUE TITLE
Feature: Showing the transactions made in the table

### ISSUE THREAD

**Issue by ilkeali25** [iron-fish/ironfish#3098]
### Description

There is a situation like this, even if the transactions are realized, the tx files are not processed and no points are given. If anyone has had a different experience than those I've seen, the room can provide information. Tasks are evaluated once a week, but why are txs not reflected on the sign?
Even if points are not given, it will be healthy to be shown in the table.

**Comment by hughy** [comment]
Please ensure that the name of the asset that you send in a transaction is the same as your testnet graffiti.

We match the asset name to the graffiti in order to display transactions and award points on the testnet leaderboard. Since the leaderboard does not track your public address there is not another way to match transactions to your account.

**Comment by ilkeali25** [comment]
There is no problem there, the transactions after the points received do not appear on the board, I meant it.
in terms of activity, thank you.

**Comment by hughy** [comment]
We only display activities that have earned points in order to show how the total is calculated.

You can use the `ironfish wallet:transactions` CLI command to show all transactions that you've sent.
