### ISSUE TITLE
i am runing  node last 48 hour, but still no reward please help

### ISSUE THREAD

**Issue by hntrader** [iron-fish/ironfish#3137]
### Description

i am runing  node last 48 hour, but still no reward please help

**Comment by Serge-GHSHCH** [comment]
Please check the node status: 
  journalctl -u ironfishd -f

Then check the miner status:
  journalctl -u ironfishd-miner -f

If it OK, then check the monitoring is ON: 
  ironfish config:set enableTelemetry true

Check ironfish status:
  ironfish status -f

You should see something like this:
Version              0.1.62 @ 4ab43f3
Node                 STARTED
Node Name            xxxxxx
Block Graffiti       xxxxxx
Memory               Heap: 78.50 MiB -> 383.42 MiB / 4.00 GiB (1.9%), RSS: 1.22 GiB (7.8%), Free: 13.33 GiB (14.7%)
CPU                  Cores: 6, Current: 1.3%
P2P Network          CONNECTED - In: 2 B/s, Out: 2.71 KB/s, peers 50
Mining               STARTED - 1 miners, 0 mined
Mem Pool             Count: 10 tx, Bytes: 20.24 KiB
Syncer               IDLE - 4.75 blocks added/sec
Blockchain           00000000001cf8f5cc1f313bfffffffffb3ddb71c4498d9434f112f0a4ffffff (123456), Since HEAD: 29s 426ms (SYNCED)
Accounts             00000000001cf8f5cc1f313bfffffffffb71c4498d9434f112f0a4ffffff (123456)
Telemetry            STARTED - 99764 <- 63 pending
Workers              STARTED - 0 -> 0 / 5 - -0.06 jobs Δ, 1.2 jobs/s

You can also get information about connection status and errors by running the following command:
  ironfish peers

**Comment by hntrader** [comment]
![Screenshot 2023-01-26 105258](https://user-images.githubusercontent.com/121235015/214924391-e32beaf0-f969-4dd7-8442-9e19422f960a.png)
looking like this

**Comment by hntrader** [comment]
![Screenshot 2023-01-26 105630](https://user-images.githubusercontent.com/121235015/214925105-89adf77e-09cc-4e56-820f-1df01dd68e27.png)

**Comment by hntrader** [comment]
![Screenshot 2023-01-26 110923](https://user-images.githubusercontent.com/121235015/214927454-ac56c3fe-474b-4306-b20a-a9b148f2a472.png)

**Comment by ygao76** [comment]
Hi @hntrader  I saw you have testnet points https://testnet.ironfish.network/users/291434 I will close the issue now. Feel free to reopen it if you still have issue with testnet points.
