### ISSUE TITLE
can not import my previous wallet

### ISSUE THREAD

**Issue by Amirhosein1616** [iron-fish/ironfish#3385]
### What happened?

i can't import my wallet, I get an error!!!!!!
![ironfish](https://user-images.githubusercontent.com/123482616/218249717-54b3130f-15f2-4b45-86c3-68460b0d91c5.jpg)

### Version

0.1.67

### Graffiti

amir1616

**Comment by wd021** [comment]
the wallet import/export is now different. it will show as a bech32 string that looks something like `ironfishaccount0000....`

**Comment by Amirhosein1616** [comment]
Have I lost everything I had? I don't think it's a simple thing to easily say that the method has changed! Or at least put a solution for the old version!

**Comment by wd021** [comment]
you can actually still import with your spending key. if you use `wallet:import [spending key]`, it'll work.

**Comment by Amirhosein1616** [comment]
Thank you, it is entered but the balance shows 0. There is no solution to fix it? Or is this a bug?

**Comment by wd021** [comment]
It's probably incorrect because it's still scanning. If you run `status` you can see the state of your account - it will show you up to which block it's done scanning. If for whatever reason it's stuck and not scanning, you can always run `wallet:rescan --reset` and it will initiate a rescan of your wallet.

**Comment by Amirhosein1616** [comment]
Thank you for your guide. Solved
