### ISSUE TITLE
Transaction is made but Wallet balance not deducted or reduced.

### ISSUE THREAD

**Issue by 87sqar** [iron-fish/ironfish#3488]
### What happened?

Hi I made two transactions from my account fee paid but not deducted from my wallet balance. check it

![error](https://user-images.githubusercontent.com/91259583/220198885-ec93c333-b226-45e7-903a-db9b5a4602da.jpg)

**Comment by hughy** [comment]
The displayed balance doesn't change because the transactions are in a pending state. If you use `ironfish wallet:balance --all` you can see the effect on your 'pending' balance. The 'confirmed' balance displayed here is the balance of your account using only on-chain transactions.

We're working on making the differences in balances clearer!

**Comment by hughy** [comment]
#3515 adds calculation of 'available' balance: the amount that you can send in a transaction at the given time.
