### ISSUE TITLE
Node stops responding to commands

### ISSUE THREAD

**Issue by jesper-bylund** [iron-fish/ironfish#43]
Following the instructions from the readme files, no responses appear from the CLI on my M1 MBP.

I can connect to the IronFish network, but nothing else:

account:giveme asks me for my email, then does nothing.
accounts:balance never responds.
miners:start just starts a loading state and never gives any additional info.

I only noticed something was wrong and not by design seeing a different response from accounts:giveme in the documentation.

Anyone else having similar issues? Tips on debugging?

**Comment by dguenther** [comment]
Hmm, just to try debugging, try starting the node with `--bootstrap "''"` (or set `bootstrapNodes` in your config to an empty list), then try something like `accounts:balance` that shouldn't require the network and see if it responds. I'm curious if the node is getting overloaded with messages so that it can't handle RPC communications.

**Comment by jesper-bylund** [comment]
Yep @dguenther , that worked perfectly. Now every command is basically instant.

**Comment by dguenther** [comment]
This should be significantly improved in `master` and the latest release. The faucet will likely still have issues until block syncing is updated, though. I'm going to close this issue, but if you're still seeing commands like `status` being unresponsive, feel free to reopen it.
