### ISSUE TITLE
Account balance shows as zero, incorrectly.

### ISSUE THREAD

**Issue by hodls** [iron-fish/ironfish#505]
Account balance shows as zero, incorrectly. See screenshot below:
- Pink is original balance
- yellow is debited (gas plus send amount)
- Red is new balance. Zero?

<img width="1487" alt="Bug" src="https://user-images.githubusercontent.com/43222627/144314377-a503b2b7-44ea-4c66-8238-452ae71e671d.png">

**Comment by hodls** [comment]
After playing around with this a little, I am able to reproduce the error by paying transactions too quickly, without waiting long enough between transactions.

›   Error: Request failed (400) insufficient-balance: Please wait a few seconds for your balance to update and try again

**Comment by deekerno** [comment]
This is due to how notes are consumed for transactions on the node. When creating a transaction, notes are used as inputs to furnish the desired transaction amount plus the fee. You will receive your change in the form of output notes which are then stored in your wallet, but _only_ after your transaction has been confirmed by the network and included in a block.

That being said, there is potential for improving the wording regarding balances, and we'll look into that.
