### ISSUE TITLE
Transaction link doesn't work at the same time when it's received

### ISSUE THREAD

**Issue by helidze** [iron-fish/ironfish#552]
**STR:**

1. Start node
2. Start mining
3. Make the whole procedure of the command "ironfish accounts:pay"
4. Copy & Open transcation link

**A.R:** 
<img width="1664" alt="Screenshot 2021-12-03 at 00 44 12" src="https://user-images.githubusercontent.com/17140053/144585382-d384db4b-a161-4a86-ba37-d0f9621ba453.png">

**E.R:** Some pending transaction with info

**Comment by deekerno** [comment]
This is due to the nature of how transactions work in a blockchain; they have to be included as part of a mined block, so they will not be immediately found on the Block Explorer. Also, if you look closely, there is a sentence after the link that status that the transaction will take a few minutes to show in the explorer.
