### ISSUE TITLE
Accounts pay bugs

### ISSUE THREAD

**Issue by ilhamm02** [iron-fish/ironfish#587]
I made 2x transactions with an initial balance of 500. Both with an amount of 0.00000001. The first one comes out hashed but it can't be searched in explorer I don't know this is normal or not considering it's part of ironfish network privacy. However, when I did the second one I looked like usual however, the available balance became 480. Then a few minutes later it changed to normal again to 500. Here's the screenshot while i'm trying to spamming. 
![image](https://user-images.githubusercontent.com/24799581/144754135-3fe90385-4b1e-4524-a902-d5a17331f8ba.png)

**Comment by deekerno** [comment]
This is due to how notes are consumed for transactions on the node. When creating a transaction, notes are used as inputs to furnish the desired transaction amount plus the fee. You will receive your change in the form of output notes which are then stored in your wallet, but only after your transaction has been confirmed by the network and included in a block.

That being said, there is potential for improving the wording regarding balances, and we'll look into that.
