### ISSUE TITLE
Another node is using the database, waiting for that node to close.

### ISSUE THREAD

**Issue by khuongtran1904** [iron-fish/ironfish#611]
I don't know if this is an error but i cant connect. Is there any way to fix this? Thanks.

**Comment by deekerno** [comment]
If you try to start a node when there is a node already running, this message will appear. However, sometimes the database does not unlock properly due to an incomplete shutdown. If you're completely sure that another node is not running, then you should look into the databases directory inside the Iron Fish data folder and remove any `LOCK` files that you may see and then try to start the node again.
