### ISSUE TITLE
I successfully mined block, but after I restarted the computer, the whole chain got stuck?

### ISSUE THREAD

**Issue by kevinbubu** [iron-fish/ironfish#650]
I successfully mined a block, but I accidentally restarted the machine. And then the chain got stuck.

Log:
```
Successfully mined block 0000000001aba0d54174dc946b4b1fb523d7c1e9622b483e7db1df8109fc1cbb (13561) has 2 transactions
Failed to add mined block to chain with reason Invalid spend
^CShutting down node after SIGINT
Not connected to the Iron Fish network
```

Before restarting, I checked the status and it showed 1mined. After I starting  it showed 0mined. How to recover?

**Comment by deekerno** [comment]
The block that you mined in this output was considered invalid due to a bug in transaction processing and it was not included as part of the main chain. This was a widespread issue that we fixed as part of v0.1.11.

Additionally, the `Mining` part of the status output shows the amount of blocks mined in the current session. That particular number starts at zero every time you run your node. To see your mined blocks and determine how many blocks have been added to the main chain, you can use `ironfish miners:mined`.
