### ISSUE TITLE
Spend Causes "Available to Spend" to Decrease to 0 While Transaction is Confirming

### ISSUE THREAD

**Issue by zkstorm** [iron-fish/ironfish#677]
**Issue**

I sent 1 $IRON with a fee of 1 $ORE to another account of mine. After sending, I ran "ironfish accounts:balance" on the sender's account and noticed that my available to spend had dropped from 20 $IRON to 0 $IRON. 

Note that after confirmation, it did return to 19 $IRON, as expected. Based on other testing, it appears to decrease the available to spend balance by 20 IRON (and not necessarily all the way down to 0).

**Expectation**

I would expect only the total transaction (1 IRON, 1 ORE) to be unavailable to spend while confirming the transaction. 

**Supporting Information**

https://explorer.ironfish.network/transaction/012e91124435d18559a50be123887494534ba0147f1f0a95974d803bf5b2a99d

![Screen Shot 2021-12-09 at 10 52 38 PM](https://user-images.githubusercontent.com/84751530/145519566-fababad6-f1f9-4c09-844a-ced73c77948a.png)
![Screen Shot 2021-12-09 at 10 57 47 PM](https://user-images.githubusercontent.com/84751530/145519690-d3a01aaa-26d7-42b3-9e9e-db05dbc805aa.png)

**Comment by deekerno** [comment]
This is due to how notes are consumed for transactions on the node. When creating a transaction, notes are used as inputs to furnish the desired transaction amount plus the fee. You will receive your change in the form of output notes which are then stored in your wallet, but only after your transaction has been confirmed by the network and included in a block. The balance _during_ your transaction is the sum of all of the unconsumed notes; the balance _after_ your transaction has been confirmed includes the aforementioned balance plus the output notes (if any) of said transaction.

That being said, there is potential for improving the wording regarding balances, and we'll look into that.
