### ISSUE TITLE
Missing rewards for mining blocks

### ISSUE THREAD

**Issue by freealeks80** [iron-fish/ironfish#694]
Hi!

Seems like these Successfully mined blocks didn't result in increase of balance 

Dec 10 03:38:12 s426179 yarn[1496991]: Successfully mined block 00000000014e6baff3807036d1eae36bcab00f883e8271757f5acd264ff3e002 (15819) has 2 transactions
Dec 10 09:10:23 s426179 yarn[1496991]: Successfully mined block 0000000006848e216a4773ee942529ac9a2dfad02d421462431e419ad61a9ca7 (15934) has 2 transactions
Dec 10 19:40:02 s426179 yarn[1496991]: Successfully mined block 0000000002a2c75c9e3ae458305f15a09fbf61c9a64cc0e4ca071617ee9b6517 (16343) has 4 transactions

**Comment by dguenther** [comment]
Your mined blocks need to be included on the main chain in order to receive an increased balance -- if you run miners:mined, do any of those blocks show up with `MAIN`?

We also have some bugs right now where blocks may mine successfully, but fail verification when attempting to add them to the chain -- you'd see that in your node logs with errors like `Failed to add mined block to chain with reason`

**Comment by freealeks80** [comment]
ironfish  miners:mined takes too much time.

Checked with 
ironfish chain:block gives
No block found with hash 00000000014e6baff3807036d1eae36bcab00f883e8271757f5acd264ff3e002
No block found with hash 0000000006848e216a4773ee942529ac9a2dfad02d421462431e419ad61a9ca7
No block found with hash 0000000002a2c75c9e3ae458305f15a09fbf61c9a64cc0e4ca071617ee9b6517

any way to recover and get back to MAIN?
Thanks
