### ISSUE TITLE
Blockchain lost my mined block #4343

### ISSUE THREAD

**Issue by alterkahn** [iron-fish/ironfish#840]
Recently I noticed that my account balance was changed again and one of my mined blocks disappeared from the chain data, despite both official and unofficial explorers showing it: 

https://testnet.ironfish.network/users/1780 
https://www.ironfishnet.com/graffiti/alterkahn

![Снимок экрана 2021-12-28 в 00 38 47](https://user-images.githubusercontent.com/67752860/147511895-deeb7dd8-b57f-49f2-90e4-a2ca0eabd400.png)

![Снимок экрана 2021-12-28 в 00 39 01](https://user-images.githubusercontent.com/67752860/147511898-3a1d96f4-cc6c-43c8-9bdb-76fbc703bc82.png)

```
ironfish accounts:publickey

Account: alterkahn, public key: 39423d564734cffa2a79bcd1b9da59a3c392de0d3d264ca93a85394231aeb4facd43dd59d7a5cd8367a84c

ironfish accounts:balance

The account balance is:    $IRON 459.00000015 ($ORE 45,900,000,015)
Amount available to spend: $IRON 459.00000015 ($ORE 45,900,000,015)              # instead of ~480 $IRON for 24 mined blocks

ironfish miners:mined

Scanning for mined blocks...
Scanning for mined blocks from 1 -> 41920
00000000269a96e6788f5eab84c91f26dafb4e1939638a1edd4bbd6c468a78be alterkahn 20 MAIN 3668: view in web # no block 4343 after 3668, the next one is 12667
0000000006ee9c0ee10b490914983003d2f1ea67356f4bfe0ffb7f874ad728fd alterkahn 20 MAIN 12667: view in web
000000000491e6c05e72c636ba0221d9c78e79443ab20cc72e532843d07a7ee0 alterkahn 20 MAIN 13534: view in web
0000000001bfcd7d1b40b0ddb1415c653b8e5996ea5596e02edae7d5ba959359 alterkahn 20 MAIN 14517: view in web
00000000059d8eb5649f2b8074236fc9a5e6eecb4eedca4f1002f58691e36cf6 alterkahn 20 MAIN 14635: view in web
000000000f411dee5e196f85bdcb7af9563657a2e2cf1646b710432aa696cd9a alterkahn 20 MAIN 16266: view in web
0000000005cae2d3ed3cc407bbe09bd867f911044d3189be6de4377d860079c4 alterkahn 20 MAIN 16399: view in web
000000003af4c2ddeeb20993744da8779bcbdd83e51003e70d927117f920f3d8 alterkahn 20 MAIN 16966: view in web
0000000009302d91bb3be026ef7067eec757c495924e0d5c84c797ee6b74c5ac alterkahn 20 MAIN 24782: view in web
000000000904826e4b9906c1db5a7332f047f2353a8548d97fcea7645d5d2cd9 alterkahn 20 MAIN 25933: view in web
0000000000feddfad64213c2d5340ad18479983e9d1fb1146ef695cd0f2d8bd1 alterkahn 20 MAIN 25967: view in web
000000000403431f8dba6fb56ce7d3c269b2b839ca0f6eb02478a1250342a1a3 alterkahn 20 MAIN 27057: view in web
0000000004c9336a03c0657c1e8164e74ac2fd937147cc8af5edda02e0ecec39 alterkahn 20 MAIN 27220: view in web
000000000666e97d1dd31e62d2c3f749edad9ea02be5758596413d32b74833b6 alterkahn 20 MAIN 28799: view in web
00000000021a0b1a8c8ccfc00cc279ae3dd06b3d08889af2d849af0126c99b68 alterkahn 20 MAIN 29687: view in web
00000000050503b9327f78c0dc7f68b5a1cd8a0d6f93df191bd3a825f10e7455 alterkahn 20 MAIN 31064: view in web
0000000004c2e4d64c5892eb73e53b78f0810c60ab86f801e25d80b93b227860 alterkahn 20 MAIN 31972: view in web
00000000034278df1765bfd9ef629bb96e33179999848c58e33f345d70293aad alterkahn 20 MAIN 32972: view in web
00000000074e675841d86547bb0b9c8f97f61191bfb721be523f5abfa14162a4 alterkahn 20 MAIN 33039: view in web
00000000037e308ecab25491d83110cee47f60efbe1e4a1c691040d4845aec37 alterkahn 20 MAIN 34876: view in web
00000000003a71f68d06a544068be5fbd6a8d242dc7e2feb0b966addca9adf08 alterkahn 20 MAIN 35259: view in web
0000000000c1c2a99f5cc64f683424970765f0da2e99e85f642e9c00788698ff alterkahn 20 MAIN 38474: view in web
0000000000cec6cabfe35ae985228cb80423d84dbac3a3291960ae00ba587e51 alterkahn 20 MAIN 40195: view in web
```
I definitely have seen that block in CLI earlier, a few updates ago.

**Comment by dguenther** [comment]
If you run `ironfish chain:block 4343` on your node, does it show a block with graffiti `alterkahn` and metadata `main: true`?

If so, is it possible that the block was mined using a different account that's no longer on your node?

**Comment by alterkahn** [comment]
```
ironfish chain:block 4343
yarn run v1.22.17
$ yarn build && yarn start:js chain:block 4343
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run chain:block 4343
{
  "block": {
    "graffiti": "alterkahn",
    "hash": "0000000033736f1e2205a6ecbc1fd988c46210cfe0d591eafb08dbe2fe33a3ca",
    "previousBlockHash": "0000000016f8f787970dbf42ebdd4a3114a4ae75fecddc4ecbb090b461825011",
    "sequence": 4343,
    "timestamp": 1638404155148,
    "transactions": [
      {
        "signature": "f507ba22379a76da6c30300145b130f8199f738960f27a5618c1e905a9e628d5ae19204b66f833fbf86e5365c438d50e73ef2d758e1a6ecb9921abb42b1ab806",
        "hash": "645fe8eec49dca6397dc843ae4f6698bd1510c7669d942f6a9b94dd8d099f11e",
        "fee": "-2000000000",
        "spends": 0,
        "notes": 1
      }
    ]
  },
  "metadata": {
    "main": true
  }
}
Done in 2.96s.
```

**Comment by alterkahn** [comment]
The account was always the same

**Comment by dguenther** [comment]
Got it, so your node agrees with the explorer that the block is on the main blockchain and has your graffiti, but it looks like it's not getting decrypted as expected by your account key.

We don't have a great tool yet for testing whether a block is directly decryptable, I'll ping you on Discord and see if you could share your account key with me for debugging.

**Comment by dguenther** [comment]
I did some investigation into this using the key you sent me. As you mentioned, I wasn't able to decrypt any notes on block 4343, hash `0000000033736f1e2205a6ecbc1fd988c46210cfe0d591eafb08dbe2fe33a3ca`. The `miners:mined` command checks forked blocks as well, so if block 4343 was a fork in your database, it should have appeared in your `miners:mined` output.

These are the possible causes I can think of:
#### The miner's reward transaction was generated by a different account
A different default may have been set for a time due to a bug, or the account may not have been imported between database resets. I don't think we currently display the account used when generating a new miner's reward transaction, so that would be a good change for us to make. Also, we display the account name frequently, but it's possible that the same account name could be used for two different keys, so we should display a unique identifier along with the account name.

It's also possible that another node may have been mining with the same graffiti. I'd have to think a bit more about whether there's anything we could do to detect or inform a node of this.

#### The miner's reward on the block was replaced with a different transaction
I spent some time attempting to replace a transaction on an existing block, but couldn't find a way to do so without requiring the merkle tree to change, which changes the block hash and requires all subsequent block hashes to change. I can't rule out that I missed a bug in verification, but I tried all scenarios I could think of.

Still, it seems unlikely that this is the case, since I'd expect the original unmodified block to still be in your database.

We can make a change to null out the `hash` field sent over the network. It's not a necessary field and shouldn't be trusted by clients, but I have no evidence this is causing any bugs now.

#### The transaction was generated using your spend key, but it's not decryptable using your view key
I'd have to see more conclusive evidence to conclude there's an issue with the transaction cryptography, for example writing a script to generate transactions in a loop and show that some of them can't be decrypted. This is the first time we'd be speculating that this is the case, and the cryptography library has been well-tested by zcash already.

### Follow-up

Unfortunately there isn't enough evidence here for me to reach a conclusion on what happened or what needs fixing, so I have to close this issue as inconclusive. But as mentioned above, there are some changes I can make to help with debugging a similar issue in the future. If you're able to find a different block 4343 that you're able to decrypt and has the same graffiti, feel free to reopen the issue, otherwise if I can get the changes in and we see this happen in the future, we should have more info to debug it further.
