### ISSUE TITLE
status -f text formatting

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#845]
i found that this one state of  cli which showing "status -f" has issues with text formatting and visual refresh after windows resizes
![bug1](https://user-images.githubusercontent.com/43998465/147792343-73858893-d599-44bb-acdf-21933bbb6b6c.png)

graffiti Qualia

**Comment by NullSoldier** [comment]
Yeah, this is unfortunately just a side effect of using tricky rendering of live terminal. There isn't any bug here exactly. We can improve this by using full curses rendering of the terminal using blessed, or try to upgrade to oclif-core down the line since we use a third party library to do this terminal rendering.
