### ISSUE TITLE
config:set removes leading `-=` from blockGraffiti

### ISSUE THREAD

**Issue by e-kolpakov** [iron-fish/ironfish#899]
### What happened?

`ironfish config:set blockGraffiti` removes leading `-=` from the value.

```
/usr/src/app# ironfish config:set blockGraffiti "aaa" && ironfish config:get blockGraffiti
"aaa"  <--- Goood
/usr/src/app# ironfish config:set blockGraffiti "-aaa" && ironfish config:get blockGraffiti
"-aaa" <--- Good
/usr/src/app# ironfish config:set blockGraffiti "-=aaa" && ironfish config:get blockGraffiti
"aaa" <--- Bad, should be -=aaa

/# cat ~/.ironfish/config.json 
{
    "blockGraffiti": "aaa"
}
```

Setting block graffiti with leading -= via `--graffiti` command line argument works as expected

### Version

0.1.19

**Comment by IgorLesnevskiy** [comment]
@e-kolpakov the problem is in the `@oclif/parser` package, who sanitizes the value during parsing. I've spent some time working around the problem and wasn't able to find the solution. As an option, you can throw an error when somebody tries to use a prohibited combination of symbols - `/(^\-=)/`. If it's acceptable for you, I can create a merge request. However, this is not the best solution. You can also try to migrate to "@oclif/core" (since you use an outdated package), but they didn't change much regarding the problem, as far as I can see.

**Comment by wd021** [comment]
yea took a look at this as well and came to the same conclusion as @IgorLesnevskiy. Any solution will require some heavy lifting. I'd recommend simply adding validation to graffitis on signups to prevent these special chars from leaking through.

**Comment by lwisne** [comment]
This one will be a nofix for now.
