### ISSUE TITLE
Site: block explorer transaction double string

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#912]
### What happened?

![2022-01-19_22-06-36](https://user-images.githubusercontent.com/43998465/150198082-0fdc7462-20ff-4b0c-b780-f84d45b477eb.png)
Sometimes block explorer just show 2 transaction lines.
Atleast i've seen on very old block
Graffiti: Qualia

### Version

v0.1.19

**Comment by NullSoldier** [comment]
https://explorer.ironfish.network/blocks/0000000011ccca0fc9fef5b90173243552c38147c031d4a0ae04e35095df91b1

This issue is caused by a bug in our syncing. If you click each transaction, you'll notice one is lower case, and one is upper case. This issue is fixed but we need to re-sync the entire chain. That's planned on February 14th, as outlined in this discord message. https://discord.com/channels/771503434028941353/816795744680935445/940338404669947955

Thanks for the bug report!
