### ISSUE TITLE
2 strange transactions for mined block

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#948]
### Description

not expected 2 transaction while successfully mined a block:

> https://explorer.ironfish.network/blocks/00000000000a8ce7be777839222f5c6377afa42d976b74ab86cd535355f2084c

first transaction getting 2000500000 $ORE for a block **[not expected amount for getting block]**
second transaction is 500000 $ORE fee for first transaction **[strange way to compensate first transaction]**

**Comment by deekerno** [comment]
I investigated this issue to determine whether this was a faucet transaction, which it was not. Thus, it's likely that someone manually entered the above number as the fee for the transaction, even though it is certainly more than the default 1 $ORE. Since the block reward to the miner is currently set to 2000000000 $ORE, it has to include the requisite amount to offset the fees for the transaction. I'm monitoring the explorer to ensure that this aren't more occurrences of this type.
