### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by b0b1kk** [iron-fish/ironfish#961]
### What happened?

A bug happened!
You can find error 1 below:

root@ironfish:~# ironfish faucet
yarn run v1.22.17
$ yarn build && yarn start:js faucet
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run faucet

::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Enter your email to stay updated with Iron Fish: *******@gmail.com
Collecting your funds... Too many faucet requests
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Version

0.1.21 @ src    

### Relevant log output

```shell
root@ironfish:~# ironfish faucet
yarn run v1.22.17
$ yarn build && yarn start:js faucet
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run faucet

::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Enter your email to stay updated with Iron Fish: *******@gmail.com
Collecting your funds... Too many faucet requests
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by deekerno** [comment]
Do you have any other information about this error? Have you used the faucet before? If so, how many times have you requested funds?

**Comment by leanthebean** [comment]
We added a throttle because people started to write scripts to request funds from the faucet. If you try to get more funds from the faucet, you'll see that error.

Although, I don't think it should have failed with `error Command failed with exit code 1.`

**Comment by wd021** [comment]
This actually happens when you hit both api errors of `Too many faucet requests` and `You entered an invalid email.`.

<img width="615" alt="Screen Shot 2022-02-18 at 9 22 16 PM" src="https://user-images.githubusercontent.com/2752586/154794818-3016c0d3-0a82-4ab6-910d-f3a634ce8377.png">

<img width="658" alt="Screen Shot 2022-02-18 at 9 13 22 PM" src="https://user-images.githubusercontent.com/2752586/154794828-79ff5b63-fbe7-41d9-80a8-a505afc5fab2.png">

All error in getFunds() in faucet.ts will result in `this.exit(1)`. Here's the PR fix -> https://github.com/iron-fish/ironfish/pull/1048

**Comment by NullSoldier** [comment]
We decided that this is not an actual bug. When any command exits with a non zero exit code, our developer tooling prints this error out. There's no easy fix as Yarn does not have a way to suppress these for one invocation of yarn. Since you are running from source, you are using engineering tooling, so you'll unfortunately have to deal with this level of verbosity.
